// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PressureMeasurementApplication.Utils;

namespace PressureMeasurementApplication.Migrations
{
    [DbContext(typeof(SQLiteDataContext))]
    [Migration("20210121040815_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PressureMeasurementApplication.Model.DataModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Data")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MissionModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionModelId");

                    b.ToTable("DataModel");
                });

            modelBuilder.Entity("PressureMeasurementApplication.Model.MissionModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MissionModel");
                });

            modelBuilder.Entity("PressureMeasurementApplication.Model.DataModel", b =>
                {
                    b.HasOne("PressureMeasurementApplication.Model.MissionModel", null)
                        .WithMany("DataModels")
                        .HasForeignKey("MissionModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PressureMeasurementApplication.Model.MissionModel", b =>
                {
                    b.Navigation("DataModels");
                });
#pragma warning restore 612, 618
        }
    }
}
